apiVersion: minecraft.mcop.co-salt.com/v1alpha1
kind: MinecraftServer
metadata:
  name: hard-test-server
  namespace: minecraft-operator-system
spec:
  version: "1.21.5"
  difficulty: "normal"
  serverName: "hardWorld"
  storage: "2Gi"
  hardcore: true