apiVersion: minecraft.mcop.co-salt.com/v1alpha1
kind: MinecraftServer
metadata:
  name: okasi
  namespace: minecraft-hard
spec:
  version: "1.21.5"
  difficulty: "peaceful"
  serverName: "okasi"
  storage: "2Gi"
  hardcore: false