apiVersion: minecraft.mcop.co-salt.com/v1alpha1
kind: MinecraftServer
metadata:
  name: test-server
  namespace: minecraft-operator-system
spec:
  version: "1.21.5"
  difficulty: "easy"
  serverName: "testWorld"
  storage: "2Gi"
  hardcore: false