apiVersion: minecraft.mcop.co-salt.com/v1alpha1
kind: MinecraftServer
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: minecraftserver-sample
spec:
  # TODO(user): Add fields here
