# pvc-rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pvc-destroyer-binding
  namespace: minecraft-hard            # Role と同じ NS
subjects:
- kind: ServiceAccount
  name: hardcore-bot-sa                # ② で作成した SA
  namespace: minecraft-operator-system # ←★ Bot の NS を明示！
roleRef:
  kind: Role
  name: pvc-destroyer                  # ③ の Role 名
  apiGroup: rbac.authorization.k8s.io
