# pvc-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pvc-destroyer          # 任意名
  namespace: minecraft-hard    # PVC がある NS
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "delete"]
